### PR TITLE
Create docker image

### PR DESCRIPTION
**Pull request by charalamm**
Added code for creating a docker image to be used when deploying the terracotta server. It has been used in an azure container app and it had really good results.

### CODE REVIEW

**Comment by charalamm** [comment]
@dionhaefner 

> What's the concrete use case for this? It looks like it's meant for production, but why use terracotta serve then instead of a real webserver with concurrency?
The intention is to use the docker image in a containerized deployment. I am going to use that image with azure container apps.
Good point about the real server. I added `gunicorn` but not sure if it is enough. Do you mean servers like nginx?

**Review by dionhaefner — CHANGES_REQUESTED** [review]
Thanks, this looks better now. 

1. Could we please move the makefile and dockerignore under a `docker/` subfolder to keep this self-contained? (You might have to move the build context one level deeper)
2. Please add a minimal example on how to use this to `docker/README.md`.

**Comment by charalamm** [comment]
> 1. Could we please move the makefile and dockerignore under a `docker/` subfolder to keep this self-contained? (You might have to move the build context one level deeper)
> 2. Please add a minimal example on how to use this to `docker/README.md`.

Thanks @dionhaefner for the recommendations, I added them.

**Comment by dionhaefner** [comment]
LGTM, thanks

**Review by dionhaefner — APPROVED** [review]

**Pull request merged**
