### PR TITLE
Update wsgi.rst

### PR DESCRIPTION
**Pull request by YuhangCh**
Modify the sock position and application entry to correspond to the context

### CODE REVIEW

**Comment by dionhaefner** [comment]
Thank you for the contribution. Could you give some context with that? Why is it preferable to have the socket in the same location as the data?

**Comment by YuhangCh** [comment]
According to the explanation of the service file:
- Binding to a unix socket file terracotta.sock in the working directory

**Comment by dionhaefner** [comment]
We also have

```
WorkingDirectory=/mnt/data
```

so the socket file should already go there. Did you find that to not be the case?

**Comment by YuhangCh** [comment]
No, the socket file is already in the working directory. Adding an absolute path seems redundant.I removed it.

**Comment by dionhaefner** [comment]
Looks good. Thanks!

**Pull request merged**
